repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        name: Check if source code is formatted
        exclude: src/main/python/{{cookiecutter.package}}/generated/
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
      - id: isort
        name: Check if import are optimized
        exclude: src/main/python/{{cookiecutter.package}}/generated/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Check for source code smells
        exclude: src/main/python/{{cookiecutter.package}}/generated/
        args:
          - --ignore=E501
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        name: Check for type errors in code
        exclude: src/main/python/{{cookiecutter.package}}/generated/
